app/uk/gov/hmrc/exports/connectors/CustomsDeclarationsConnector.scala
app/uk/gov/hmrc/exports/controllers/ExportController.scala
app/uk/gov/hmrc/exports/controllers/HeaderValidator.scala
app/uk/gov/hmrc/exports/controllers/NotificationsController.scala
app/uk/gov/hmrc/exports/controllers/SubmissionController.scala
app/uk/gov/hmrc/exports/metrics/ExportsMetrics.scala
app/uk/gov/hmrc/exports/models/DeclarationNotification.scala
app/uk/gov/hmrc/exports/models/ErrorResponse.scala
app/uk/gov/hmrc/exports/models/ExportStatus.scala
app/uk/gov/hmrc/exports/repositories/NotificationsRepository.scala
app/uk/gov/hmrc/exports/repositories/SubmissionRepository.scala
app/uk/gov/hmrc/exports/services/ExportsService.scala
build.sbt

PR covers log errors for all services and controllers.
Every class has his own logger to make it more readable in logs, without using this general one.
Coverage wend down, changed to 94%. Loggers don't have tests. It'll be covered in next iterations.

CEDS-1141 Add log errors to all application

---

app/uk/gov/hmrc/exports/repositories/NotificationRepository.scala

This was breaking notifications in DEV

CEDS-1330: remove the unique key on notification datetime

---

project/AppDependencies.scala
project/plugins.sbt
test/integration/uk/gov/hmrc/exports/base/IntegrationTestSpec.scala
test/unit/uk/gov/hmrc/exports/base/UnitSpec.scala
test/unit/uk/gov/hmrc/exports/config/AppConfigSpec.scala
test/unit/uk/gov/hmrc/exports/connectors/CustomsDeclarationsConnectorSpec.scala

PR cover upgrade libraries and removing deprecated hmrctest.
One class from this library is added to our codebase (UnitSpec) because a lot of tests are based on this.

CEDS-1219 Upgrade for libraries and get rid of hmrctest

---

app/uk/gov/hmrc/exports/models/declaration/ConsignmentReferences.scala
app/uk/gov/hmrc/exports/models/declaration/DUCR.scala
app/uk/gov/hmrc/exports/models/declaration/submissions/Submission.scala
app/uk/gov/hmrc/exports/services/WcoMapperService.scala
app/uk/gov/hmrc/exports/services/WcoSubmissionService.scala
app/uk/gov/hmrc/exports/services/mapping/goodsshipment/GoodsShipmentBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/goodsshipment/PreviousDocumentsBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/goodsshipment/UCRBuilder.scala
test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/declaration/FunctionalReferenceIdentificationBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/GoodsShipmentBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/PreviousDocumentsBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/UCRBuilderSpec.scala
test/util/testdata/ExportsDeclarationBuilder.scala
test/util/testdata/SubmissionTestData.scala

With this change:
* DUCR will map to the first item of the `GoodsShipment.PreviousDocuments` list
* LRN stays as is
* An Optional personal UCR will, if available, will map to the
`GoodsShipment.UCR.TraderAssignedReferenceID`

CEDS-1475 Make DUCR mandatory and personal UCR optional

---

app/uk/gov/hmrc/exports/controllers/NotificationController.scala
app/uk/gov/hmrc/exports/services/NotificationService.scala
test/unit/uk/gov/hmrc/exports/base/UnitTestMockBuilder.scala
test/unit/uk/gov/hmrc/exports/controllers/NotificationControllerSpec.scala
test/unit/uk/gov/hmrc/exports/services/NotificationServiceSpec.scala

We have a technical debt ticket to link notifications to submissions/declarations by declaration ID.
At first we suggested adding the declaration ID to each notification but I'm not sure this is completely necessary. I think the "conversation ID" acts as an "Action ID". We can simplify the look up by using this instead.
Whilst I'd prefer if we created the "action ID" ourselves I think its fine for now

CEDS-1622 Remove MRN dependency for Notifications

---

app/uk/gov/hmrc/exports/controllers/NotificationController.scala
app/uk/gov/hmrc/exports/models/declaration/notifications/Notification.scala
app/uk/gov/hmrc/exports/models/declaration/submissions/SubmissionStatus.scala
test/component/uk/gov/hmrc/exports/base/ComponentTestSpec.scala
test/unit/uk/gov/hmrc/exports/models/declaration/submissions/SubmissionStatusSpec.scala
test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala
test/util/testdata/NotificationTestData.scala

This is part one - adding `actionId` and `status` to the Notification and populating these fields from `conversation Id` and `function/name Code`
Part two will be updating the FE to migrate to these new fields.
Part three will be to remove the redundant fields from the BE.
Hopefully this will minimise disruptions while migrating the change.

CEDS-1691 - rename fields in Notification

---

app/uk/gov/hmrc/exports/controllers/NotificationController.scala
app/uk/gov/hmrc/exports/models/declaration/notifications/Notification.scala
app/uk/gov/hmrc/exports/models/declaration/submissions/Action.scala
app/uk/gov/hmrc/exports/repositories/NotificationRepository.scala
app/uk/gov/hmrc/exports/repositories/SubmissionRepository.scala
app/uk/gov/hmrc/exports/services/NotificationService.scala
app/uk/gov/hmrc/exports/services/SubmissionService.scala
app/uk/gov/hmrc/exports/services/WcoSubmissionService.scala
test/component/uk/gov/hmrc/exports/base/ComponentTestSpec.scala
test/integration/uk/gov/hmrc/exports/repositories/NotificationRepositorySpec.scala
test/integration/uk/gov/hmrc/exports/repositories/SubmissionRepositorySpec.scala
test/unit/uk/gov/hmrc/exports/base/CustomsExportsBaseSpec.scala
test/unit/uk/gov/hmrc/exports/base/UnitTestMockBuilder.scala
test/unit/uk/gov/hmrc/exports/controllers/HeaderValidatorSpec.scala
test/unit/uk/gov/hmrc/exports/services/NotificationServiceSpec.scala
test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala
test/util/testdata/ExportsTestData.scala
test/util/testdata/NotificationTestData.scala
test/util/testdata/SubmissionTestData.scala

This is second part.  Removes (now) redundant fields and also renames action.conversationId field.
This change is no longer backwards-compatible and will require clearing the `customs-declare-exports` collections.

CEDS-1691 - Rename Notification conversationId and functionCode fields

---

app/uk/gov/hmrc/exports/repositories/SubmissionRepository.scala
test/integration/uk/gov/hmrc/exports/repositories/SubmissionRepositorySpec.scala
test/util/testdata/SubmissionTestData.scala

Empty actions array in submission were indexed as null for `action.id` index. 
Moving `action.id` index as partial index only for document that have at least one action.

Index fixes

---

app/uk/gov/hmrc/exports/controllers/SubmissionController.scala
app/uk/gov/hmrc/exports/controllers/request/ExportsDeclarationRequest.scala
app/uk/gov/hmrc/exports/services/SubmissionService.scala
test/component/uk/gov/hmrc/exports/ExportsSubmissionReceivedSpec.scala
test/component/uk/gov/hmrc/exports/steps/DeclarationSteps.scala
test/integration/uk/gov/hmrc/exports/connector/CustomsDeclarationsConnectorSpec.scala
test/uk/gov/hmrc/exports/controllers/request/ExportsDeclarationRequestSpec.scala
test/unit/uk/gov/hmrc/exports/controllers/DeclarationControllerSpec.scala
test/unit/uk/gov/hmrc/exports/controllers/SubmissionControllerSpec.scala
test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala

Hopefully helps reduce the duplicate DMS submissions we are seeing in QA
- We only mark the dec as COMPLETE once it has submitted to DMS successfully
- If the DMS call fails we keep it as a draft

CEDS-1779 Ensure Back End owns Status changes

---

app/uk/gov/hmrc/exports/models/declaration/ExportItem.scala
app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/AdditionalDocumentsBuilder.scala
test/integration/uk/gov/hmrc/exports/repositories/DeclarationRepositoryTest.scala
test/integration/uk/gov/hmrc/exports/repositories/NotificationRepositorySpec.scala
test/integration/uk/gov/hmrc/exports/repositories/SubmissionRepositorySpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/AdditionalDocumentsBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilderSpec.scala
test/util/SeedMongo.scala

Now it merged with document identifier as single field
Related to https://github.com/hmrc/customs-declare-exports-frontend/pull/548

CEDS-1404 Remove obsolete fields reference-part from produce documents

---

app/uk/gov/hmrc/exports/models/Pointer.scala
test/uk/gov/hmrc/exports/models/PointerSpec.scala
test/uk/gov/hmrc/exports/services/WCOPointerMappingServiceSpec.scala

We used to have a custom json formatter that assumed that because a pointer section was numerical, then it represented a sequence index. This is not the case, some pointer field references are purely numerical and we need to handle that.
Sequence sections are now rendered in JSON as `#1` (for index 1)
e.g.
Pointer Before: `abc.1.def`
Pointer After: `abc.#1.def`
It means we can convert to and from the string/json version and retain the "section type"

CEDS-1695 Fix for Pointer Fields that have numeric codes

---

app/uk/gov/hmrc/exports/controllers/request/ExportsDeclarationRequest.scala
app/uk/gov/hmrc/exports/models/declaration/AdditionalDeclarationType.scala
app/uk/gov/hmrc/exports/models/declaration/ExportsDeclaration.scala
app/uk/gov/hmrc/exports/services/SubmissionService.scala
app/uk/gov/hmrc/exports/services/mapping/CancellationMetaDataBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/declaration/ExitOfficeBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/declaration/PresentationOfficeBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/declaration/SpecificCircumstancesCodeBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/declaration/TypeCodeBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/declaration/consignment/DeclarationConsignmentBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/ConsignmentBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/ConsignmentCarrierBuilder.scala
test/uk/gov/hmrc/exports/controllers/request/ExportsDeclarationRequestSpec.scala
test/uk/gov/hmrc/exports/models/declaration/AdditionalDeclarationTypeSpec.scala
test/uk/gov/hmrc/exports/services/mapping/CancellationMetaDataBuilderTest.scala
test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/DeclarationTypeCodeMappingSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/declaration/ExitOfficeBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/declaration/PresentationOfficeBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/declaration/SpecificCircumstancesCodeBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/declaration/TypeCodeBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/declaration/consignment/DeclarationConsignmentBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/ConsignmentBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/ConsignmentCarrierBuilderSpec.scala
test/util/testdata/ExportsDeclarationBuilder.scala

This permits Simplified Declarations following the same rules as Standard Declarations. These rules may change in subsequent stories.
As part of this change I have refactored AdditionalDeclarationType into an Enum, given there will be more of these to come I think now is a good opportunity to do it.

CEDS-1839 Permit Simplified Declarations

---

app/uk/gov/hmrc/exports/services/mapping/goodsshipment/WarehouseBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/WarehouseBuilderSpec.scala

As part of the story we have removed the `WarehouseIdentificationType`
from the user journey, but it is still required to go into the DMS
payload.
James W. and Joe will create a story to update the `hint` on the
warehouse IdentificationNumber page and to provide new validation rules
for the Warehouse type.
That ticket will be played in the following sprint.
In the meantime this change is simply not to downgrade the payload that
is sent to DMS, as DMS expects both identificationNumber and Type or
none of them.
The current Warehouse model will also be replaced in a subsequent story this sprint.

CEDS-1950 Make WarehouseIdentification backwards compatible

---

app/uk/gov/hmrc/exports/services/mapping/CachingMappingHelper.scala
app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/CachingMappingHelperSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilderSpec.scala

Bug resulted in the creation of a Classification with a None identifier
(which is not permitted).
Took the opportunity to refactor the CachingMappingHelper to reduce the
expanding list of arguments passed to the
'getClassificationsFromItemTypes' method.

CEDS-1972 - fix for bug mapping CUS code to 'Classification'

---

app/uk/gov/hmrc/exports/models/declaration/Locations.scala
app/uk/gov/hmrc/exports/services/mapping/declaration/SupervisingOfficeBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/goodsshipment/GoodsShipmentBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/goodsshipment/WarehouseBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/ConsignmentBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/DepartureTransportMeansBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/declaration/SupervisingOfficeBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/GoodsShipmentBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/WarehouseBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/ConsignmentBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/DepartureTransportMeansBuilderSpec.scala
test/util/SeedMongo.scala
test/util/testdata/ExportsDeclarationBuilder.scala

The work carried out by the splitting of the Warehouse page has been
done by reutilising the `WarehouseIdentification` model. This has proven
to be confusing and the `supervisingCustomsOffice` and
`inlandModeOfTransport` no longer belong to the WarehouseIdentification
model.
This change will require a change to the model in the FE application and
in the UAT/smoke/acceptance tests.
Also relates to: CEDS-1950, CEDS-1953, CEDS-1954

CEDS-1955 Clean up the Warehouse Model

---

project/AppDependencies.scala

This should clear problem with “No primary node is available!”.

CEDS Update simple-reactive mongo to latest version.

---

app/uk/gov/hmrc/exports/models/declaration/ExportItem.scala
app/uk/gov/hmrc/exports/models/declaration/Transport.scala
app/uk/gov/hmrc/exports/services/mapping/CachingMappingHelper.scala
app/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/ConsignmentBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/PackagingBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/CachingMappingHelperSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/ExportsItemBuilder.scala
test/util/testdata/ExportsDeclarationBuilder.scala

Changes to exports declaration model to support front-end changes to summary page to only show answers to questions asked.  This means continuing the practice of making a 'page' of answers an Option[T] - in this case replacing Lists/Sequences with Option[List/Seq]

CEDS-2083 - dont show questions not answered on summary

---

app/uk/gov/hmrc/exports/controllers/request/ExportsDeclarationRequest.scala
app/uk/gov/hmrc/exports/models/declaration/ExportsDeclaration.scala
test/unit/uk/gov/hmrc/exports/controllers/request/ExportsDeclarationRequestSpec.scala
test/util/testdata/ExportsDeclarationBuilder.scala

Changing the collection type from Set to Seq ensures that insertion order is maintained.

CEDS-1439 - maintain item ordering

---

app/uk/gov/hmrc/exports/config/AppConfig.scala
app/uk/gov/hmrc/exports/mongobee/MongobeeConfig.scala
app/uk/gov/hmrc/exports/mongobee/changesets/DeclarationsChangelog.java
project/AppDependencies.scala
test/unit/uk/gov/hmrc/exports/config/AppConfigSpec.scala

* Pretty format the AppDependencies
* Add Mongobee as our DB migration tool
This PR provides a simple example of how we would update all the existing `additionalDeclarationType` fields from `D` to `A`
The Spike work can be found here (https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=179472929) for more details.
This uses Mongobee - https://github.com/mongobee/mongobee

CEDS-2111 Add Mongobee as MongoDB db migration tool

---

app/uk/gov/hmrc/exports/models/declaration/ExportItem.scala
app/uk/gov/hmrc/exports/services/mapping/CachingMappingHelper.scala
app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/CachingMappingHelperSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemData.scala
test/util/stubs/SeedMongo.scala

This PR makes gross and net weights on the CommodityMeasure optional.  I've tested that this BE change is compatible with the existing FE by creating a draft declaration with the existing BE then switching to this branch and completing the dec and submitting it.  (i.e. db upgrades are not necessary).
Only thing that I can't check is that we can eventually submit a clearance declaration without a CommodityMeasure.   It _should_ work because the wco `Commodity` that we create is optional (both in the wco library and the customs_declaration XSD).  But that will need to be verified once we have completed and deployed the FE changes for clearance requests to QA

CEDS-2191 - Change validation on Commodity Measurements page for Clearance Requests

---

app/uk/gov/hmrc/exports/models/ead/parsers/MrnStatusParser.scala
test/unit/uk/gov/hmrc/exports/models/ead/parsers/MrnStatusParserSpec.scala

The DUCR should be the first document from the "PreviousDocuments" of type
"DCR". If exists, then we should remove that element from the
"PreviousDocuments" list

CEDS-2171 Remove main DUCR from PreviousDocuments list

---

app/uk/gov/hmrc/exports/models/declaration/ExportItem.scala
app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/PackagingBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/ExportsItemBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemData.scala
test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/PackagingBuilderSpec.scala
test/util/stubs/SeedMongo.scala

For one type of declaration all the fields in PackageInformation are
non-mandatory. Since the model is shared between all declaration types,
it needs to allow 'empty' values.
From another perspective, the target schema has these fields as optional
as well.

CEDS-2190 Change all PackageInformation fields to be optional

---

app/uk/gov/hmrc/exports/models/declaration/ExportItem.scala
app/uk/gov/hmrc/exports/services/mapping/CachingMappingHelper.scala
app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/CachingMappingHelperSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilderSpec.scala
test/util/stubs/SeedMongo.scala

For Clearance Requests, data elements '6/14 Commodity code' and
'6/8 Description of Goods' are not required in the majority of cases.
This data element is not required on clearance requests using procedure
codes 00 18 or 00 19 in D.E. 1/10.
**Relates to https://github.com/hmrc/customs-declare-exports-frontend/pull/788**

CEDS-2189 Make CommodityDetails.descriptionOfGoods optional

---

app/uk/gov/hmrc/exports/models/declaration/Transport.scala
app/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/DepartureTransportMeansBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/DepartureTransportMeansBuilderSpec.scala

This is the companion PR to https://github.com/hmrc/customs-declare-exports-frontend/pull/793
It simply discards the means of transport on departure information if the user selected the "not applicable" or none option when building the XML payload.

CEDS-2192 - ignore in-applicable means of transport on departure type

---

app/uk/gov/hmrc/exports/models/declaration/Locations.scala
app/uk/gov/hmrc/exports/services/mapping/declaration/ExitOfficeBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/declaration/ExitOfficeBuilderSpec.scala
test/util/stubs/SeedMongo.scala
test/util/testdata/ExportsDeclarationBuilder.scala

This PR makes the officeId part of OfficeOfExit optional in preparation for FE changes.
This change is OK to merge in first as it's compatible with existing (non-optional officeId) FE

CEDS-2249 - Make 'Office of Exit' optional for Clearance Requests

---

app/uk/gov/hmrc/exports/mongock/MongockConfig.scala

The default lock, locks the collection for DB migrations for 24 hours.
If the DB migration takes longer than a 3 minutes, for some reason the
connection to the collection is lost and the lock is never removed.
By providing a quick lock, it would allow the application to try and
acquire the lock at least up to 10 times.

BAU - Understand DB Migrations on Remove Environments

---

app/uk/gov/hmrc/exports/mongock/changesets/JavaCacheChangeLog.java

All country codes use the two-characters ISO code.
Looking at the length of the field we can determine which records
require a migration.
This avoids having to loop through documents already migrated.

BAU - Only do the migration if country name

---

app/uk/gov/hmrc/exports/mongock/MongockConfig.scala
app/uk/gov/hmrc/exports/mongock/changesets/CacheChangeLog.scala
app/uk/gov/hmrc/exports/mongock/changesets/JavaCacheChangeLog.java
test/it/uk/gov/hmrc/exports/mongock/changesets/CacheChangeLogSpec.scala
test/util/stubs/TestMongoDB.scala

Except adding tests for migration functions, it also fixes ChangeSets no. 005 and 006.
In the first one the problem was that non-migrated documents were not recognized
correctly and therefore the migration was not applied to them.
The problem turned out to be a `type` parameter in the search query.
In the second one the problem was that the migration could potentially be executed
on documents that were already correctly migrated, adding another level of nesting 
with every call. Additional query parameter was added to prevent such situation.

CEDS-2250 Add tests for CacheChangeLog classes

---

app/uk/gov/hmrc/exports/models/declaration/Parties.scala
test/util/testdata/ExportsDeclarationBuilder.scala

Adding new field to RepresentativeDetails.  The field is not used in constructing the XML payload - it is purely there to drive frontend navigation and validation logic.

CEDS-2065 - add new 'representing another agent' field to model

---

app/uk/gov/hmrc/exports/models/declaration/Parties.scala
app/uk/gov/hmrc/exports/services/mapping/declaration/ExporterBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/declaration/ExporterBuilderSpec.scala
test/util/testdata/ExportsDeclarationBuilder.scala

These changes introduce a new section to the `Parties` to store the answer to "is the declarant the exporter".
If the answer is "Yes" then the declarant's EORI is used in the ExporterBuilder.
These changes are a dependancy for the FE changes to come, but are backward compatible with existing FE and so can be merged in independently.

CEDS-2401 - Ask if Declarant is the Exporter

---

app/uk/gov/hmrc/exports/models/declaration/Parties.scala
app/uk/gov/hmrc/exports/services/mapping/declaration/AgentBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/declaration/AgentBuilderSpec.scala
test/util/stubs/SeedMongo.scala
test/util/testdata/ExportsDeclarationBuilder.scala

If the user is representing another agent we build the Agent from the representative EORI and the representative status.  Otherwise, we use the declarants EORI and the representative status.

CEDS-2065-rework - change to logic for AgentBuilder

---

app/uk/gov/hmrc/exports/models/declaration/notifications/Notification.scala
app/uk/gov/hmrc/exports/models/declaration/submissions/Action.scala
app/uk/gov/hmrc/exports/services/NotificationService.scala
test/unit/uk/gov/hmrc/exports/controllers/NotificationControllerSpec.scala
test/unit/uk/gov/hmrc/exports/services/NotificationServiceSpec.scala
test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala
test/util/testdata/NotificationTestData.scala
test/util/testdata/SubmissionTestData.scala

DMS sends the times in UTC time, but our BE microservice converts them
to `LocalDateTime` which strips them of the Zone information.
Converting the type to `Instant` as we did in the the Movements service
allows us to store the date from DMS as `UTC` or `Zulu time` and then on
the FE we just need to inform the view that we want to render that time
on British Time Zone `Europe/London`.
This ensures that we will see the time as `GMT/UTC` and `BST` depending
on the time of the year.
This holds true as long as DMS returns their dates in UTC.
This leaves us with a legacy time data in the `LocalDateTime` format.
I had two options:
* Update the DB, by appending the `Z` (Zero Offset time AKA Zulu Time) to
every timestamp. This is easily said than done, as the timestamps are
within an array and …

CEDS-2298 Display Time always on British time zone

---

app/uk/gov/hmrc/exports/models/declaration/ExportItem.scala

This is not really 100% required for the main FE functionality.   
I just added it to solve the problem of navigating back to the "Do you want to add?" page and pre-populating with the user's previous answer.

CEDS-2492 - add 'isRequired' answer to AdditionalInformations

---

app/uk/gov/hmrc/exports/services/mapping/CachingMappingHelper.scala
app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/AdditionalDocumentsBuilder.scala
app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/AdditionalInformationBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/AdditionalDocumentsBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/AdditionalInformationBuilderSpec.scala

Previously only doing commodity details description.
This adds same functionality to additional documents and additional information fields

CEDS-2566 - extend stripping of new-lines for text-area inputs

---

test/unit/uk/gov/hmrc/exports/base/CustomsExportsBaseSpec.scala

Remove deprecated SessionKeys userId attribute from unit tests

CEDS-2695 Remove userId from unit tests for auth migration

---

README.md
app/uk/gov/hmrc/exports/controllers/NotificationController.scala
app/uk/gov/hmrc/exports/migrations/ExportsMigrationTool.scala
app/uk/gov/hmrc/exports/migrations/MigrationRoutine.scala
app/uk/gov/hmrc/exports/migrations/changelogs/notification/MakeParsedDetailsOptional.scala
app/uk/gov/hmrc/exports/migrations/repositories/MongoRepository.scala
app/uk/gov/hmrc/exports/models/declaration/notifications/Notification.scala
app/uk/gov/hmrc/exports/repositories/NotificationRepository.scala
app/uk/gov/hmrc/exports/routines/ReattemptNotificationParsingRoutine.scala
app/uk/gov/hmrc/exports/routines/Routine.scala
app/uk/gov/hmrc/exports/routines/RoutineRunner.scala
app/uk/gov/hmrc/exports/routines/RoutineRunnerModule.scala
app/uk/gov/hmrc/exports/routines/RoutinesExecutionContext.scala
app/uk/gov/hmrc/exports/services/NotificationService.scala
app/uk/gov/hmrc/exports/services/SubmissionService.scala
conf/application.conf
precheck.sh
test/it/uk/gov/hmrc/exports/migrations/changelogs/notification/MakeParsedDetailsOptionalSpec.scala
test/it/uk/gov/hmrc/exports/repositories/NotificationRepositorySpec.scala
test/unit/uk/gov/hmrc/exports/base/CustomsExportsBaseSpec.scala
test/unit/uk/gov/hmrc/exports/controllers/NotificationControllerSpec.scala
test/unit/uk/gov/hmrc/exports/models/declaration/notifications/NotificationsSpec.scala
test/unit/uk/gov/hmrc/exports/services/NotificationServiceSpec.scala
test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala
test/util/testdata/ExportsTestData.scala
test/util/testdata/NotificationTestData.scala

Before all Notification processing was a synchronous operation. In cases
where the service can not parse a Notification due to a change in its
structure, the notification data is lost as it is not inserted into
the MongoDB.
The implemented solution is:
1) The data parsed from a notification is now optional in the data
model.
2) All notifications payloads received are persisted to Mongo if they
are parsable or not.
3) A reattempt to parse 'routine' is run at app start up (after the
database migration jobs have finished) to query all unparsed
notifications and attempt to reprocess them.
4) A new database migration job created to migrate from the non-optional
notification parsed details model to the new optional structure.

[CEDS-2800] Implement asynchronous notifications processing

---

app/uk/gov/hmrc/exports/repositories/NotificationRepository.scala

Index was incorrectly set to just contain notifications where
the details sub-document is present.
Now it is correctly set to only contain notifications where
the details sub-document is not present.

[CEDS-2800] Fix Notification index detailsMissingIdx filter

---

app/uk/gov/hmrc/exports/migrations/changelogs/notification/MakeParsedDetailsOptional.scala
app/uk/gov/hmrc/exports/repositories/NotificationRepository.scala
test/it/uk/gov/hmrc/exports/migrations/changelogs/notification/MakeParsedDetailsOptionalSpec.scala

Two of the existing indexes were built on fields that
have now been moved into a sub-document. The index
fields were changed accordingly but their names remained
the same causing a clash when applied to the
existing collections in the different environments.
The modified indexes have now been renamed to make them
distinct from the previous versions of themselves. Also
the db migration job now also deletes the old versions
of these indexes to clean up.

[CEDS-2800] Fix index naming clash of new indexes with old

---

app/uk/gov/hmrc/exports/migrations/changelogs/notification/MakeParsedDetailsOptional.scala

Currently the db migration code starts in QA but never
finishes (without throwing any errors or exceptions).
It is suspected that there might be a memory limit on
mongo on the platform that we are exceeding by trying
to run 100 update queries at a time. s
So now reducing this number to 10 to see if that makes
a difference.

[CEDS-2800] Reduce query batch size for db migrations

---

conf/application.conf

application.langs now deprecated, play.i18n.langs is provided with english language by default by the bootstrap libraries.
play.http.session.httpOnly shouldn't be required by backend services, and will be added to app-config-common by the platform teams
See [blogpost](https://confluence.tools.tax.service.gov.uk/display/TEC/2020/12/01/Cleanup+deprecated+Play+framework+configuration+keys)

CEDS-2897 remove deprecated config

---

app/uk/gov/hmrc/exports/migrations/changelogs/notification/MakeParsedDetailsOptional.scala
app/uk/gov/hmrc/exports/repositories/NotificationRepository.scala

Original definition of index 'detailsMissingIdx' used the
wrong filter (where doc exists rather than where doc does
not exist!)
Dropping index 'detailsMissingIdx' and re-creating it with
new fliter as 'detailsDocMissingIdx'.

[CEDS-2800] Drop misconfigured index

---

app/uk/gov/hmrc/exports/services/mapping/declaration/consignment/IteneraryBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/declaration/consignment/IteneraryBuilderSpec.scala

DMS rules state that if the origin country is set
to GB then the routing country must also be set as
GB.
Users are understandably unaware of this rule so
have been not setting a routing country when
exporting goods from GB to other countries.
To reduce the number of declarations falling fowl
of this and being rejected we will now automatically
set the routing country to GB if the originating
country is GB and no routing countries are specified
by the user.

[CEDS-2888] Auto set routing country to GB

---

app/uk/gov/hmrc/exports/connectors/CustomsDataStoreConnector.scala
app/uk/gov/hmrc/exports/controllers/NotificationController.scala
app/uk/gov/hmrc/exports/services/notifications/NotificationFactory.scala
app/uk/gov/hmrc/exports/services/notifications/NotificationService.scala
app/uk/gov/hmrc/exports/services/notifications/receiptactions/NotificationReceiptAction.scala
app/uk/gov/hmrc/exports/services/notifications/receiptactions/ParseAndSaveAction.scala
project/AppDependencies.scala
test/it/uk/gov/hmrc/exports/connector/CustomsDataStoreConnectorSpec.scala
test/unit/uk/gov/hmrc/exports/base/AuthTestSupport.scala
test/unit/uk/gov/hmrc/exports/base/UnitTestMockBuilder.scala
test/unit/uk/gov/hmrc/exports/controllers/DeclarationControllerSpec.scala
test/unit/uk/gov/hmrc/exports/controllers/EmailByEoriControllerUnitSpec.scala
test/unit/uk/gov/hmrc/exports/controllers/NotificationControllerSpec.scala
test/unit/uk/gov/hmrc/exports/migrations/ExportsMigrationToolSpec.scala
test/unit/uk/gov/hmrc/exports/migrations/LockManagerSpec.scala
test/unit/uk/gov/hmrc/exports/migrations/repositories/MongoRepositorySpec.scala
test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/declaration/consignment/DeclarationConsignmentBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/PreviousDocumentsBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/UCRBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/WarehouseBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/AdditionalInformationBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/notifications/NotificationFactorySpec.scala
test/unit/uk/gov/hmrc/exports/services/notifications/NotificationServiceSpec.scala
test/unit/uk/gov/hmrc/exports/services/notifications/receiptactions/ParseAndSaveActionSpec.scala

Notification parsing and then saving is now done separately from
responding to the request but it is executed in the same
ExecutionContext. Should it prove inefficient, new ExecutionContext can
be implemented at a later date.
Parsing and saving logic has been extracted from NotificationService as
this class was carrying too many responsibilities. It is now much easier
to test as well.
Being aware of incoming changes and new processes to be introduced on
the receipt of a new Notification, trait NotificationReceiptAction has
been implemented. This allows to have common interface for all these
processes.

CEDS-3036 asynchronous notification processing

---

README.md
app/uk/gov/hmrc/exports/connectors/CustomsDeclarationsConnector.scala
app/uk/gov/hmrc/exports/models/declaration/notifications/Notification.scala
app/uk/gov/hmrc/exports/models/declaration/notifications/NotificationDetails.scala
app/uk/gov/hmrc/exports/services/email/EmailSender.scala
app/uk/gov/hmrc/exports/services/notifications/NotificationFactory.scala
app/uk/gov/hmrc/exports/services/notifications/NotificationService.scala
app/uk/gov/hmrc/exports/services/notifications/receiptactions/NotificationReceiptActionsExecutor.scala
app/uk/gov/hmrc/exports/services/notifications/receiptactions/ParseAndSaveAction.scala
app/uk/gov/hmrc/exports/services/notifications/receiptactions/SendEmailForDmsDocAction.scala
test/unit/uk/gov/hmrc/exports/base/UnitSpec.scala
test/unit/uk/gov/hmrc/exports/controllers/NotificationControllerSpec.scala
test/unit/uk/gov/hmrc/exports/models/declaration/notifications/NotificationSpec.scala
test/unit/uk/gov/hmrc/exports/services/email/EmailSenderSpec.scala
test/unit/uk/gov/hmrc/exports/services/notifications/NotificationFactorySpec.scala
test/unit/uk/gov/hmrc/exports/services/notifications/NotificationServiceSpec.scala
test/unit/uk/gov/hmrc/exports/services/notifications/receiptactions/NotificationReceiptActionsExecutorSpec.scala
test/unit/uk/gov/hmrc/exports/services/notifications/receiptactions/SendEmailForDmsDocActionSpec.scala
test/util/testdata/ExportsTestData.scala

This PR implements logic necessary to obtain required data
and sending request to `email` service.
Additionally, it also integrates this process into Notification
processing "pipeline" as an action executed after successful
parsing, saving and MRN update to the related Submission.
This operation is implemented in a way that it is completely
independent from any other process.
Majority of the email sending logic was created by @udinobi .

CEDS-2975 Trigger email sending

---

app/uk/gov/hmrc/exports/config/AppConfig.scala
app/uk/gov/hmrc/exports/repositories/SendEmailWorkItemRepository.scala
app/uk/gov/hmrc/exports/scheduler/ScheduledJobModule.scala
app/uk/gov/hmrc/exports/scheduler/jobs/emails/PagerDutyAlertManager.scala
app/uk/gov/hmrc/exports/scheduler/jobs/emails/PagerDutyAlertValidator.scala
app/uk/gov/hmrc/exports/scheduler/jobs/emails/SendEmailsJob.scala
conf/application.conf
test/it/uk/gov/hmrc/exports/repositories/SendEmailWorkItemRepositorySpec.scala
test/unit/uk/gov/hmrc/exports/config/AppConfigSpec.scala
test/unit/uk/gov/hmrc/exports/scheduler/jobs/emails/PagerDutyAlertManagerSpec.scala
test/unit/uk/gov/hmrc/exports/scheduler/jobs/emails/PagerDutyAlertValidatorSpec.scala
test/unit/uk/gov/hmrc/exports/scheduler/jobs/emails/SendEmailsJobSpec.scala

Pager Duty alert triggering is split into 2 classes:
Manager and Validator.
Validator class is responsible only for determination
if PD alert should be triggered or not. 
Manager class collects all data required for Validator
and also it is responsible for triggereing the alert and
updating WorkItem document in Mongo with this 
information.
The split is also there to make it easier to test.

CEDS-3045 Pager Duty alert triggering when failing to send email

---

test/unit/uk/gov/hmrc/exports/scheduler/jobs/emails/PagerDutyAlertValidatorSpec.scala

For one the test cases Duration parameter was equal to
the threshold value. This was causing the test to fail
randomly.
As a solution, 1 second has been subtracted from this
Duration value. This small time difference is irrelevant
to the whole logic, but ensures the test case pass more
reliably.

BAU Fix PagerDutyAlertValidatorSpec instability

---

app/uk/gov/hmrc/exports/services/WcoMapperService.scala

It turned out that the most time consuming part of XML generation
was the creation of JAXBContent. Full problem description together
with solutions can be found here:
https://www.ibm.com/support/pages/jaxbcontext-initialization-takes-long-time
As you can read in one of the solutions, JAXBContext is bound to a
set of classes/packages and it can be re-used for repeatedly converting
the same model. This is why the context has been made a lazy field in
the class.
This upgrade improves XML generation step approx. 100 times.
Request handling time for Declaration submission is lowered
by approx. 50%.

BAU Improve Declaration Submission performance

---

app/uk/gov/hmrc/exports/migrations/MigrationRoutine.scala
app/uk/gov/hmrc/exports/migrations/changelogs/cache/MakeTransportPaymentMethodNotOptional.scala
test/it/uk/gov/hmrc/exports/migrations/changelogs/cache/MakeTransportPaymentMethodNotOptionalSpec.scala

Fix bug where a declaration in the cache has a TransportPayment entity with
no 'paymentMethod' field value.
Created a DB migration job to remove any TransportPayment entity with
no 'paymentMethod' field value from declarations in cache.

[CEDS-3477] Bug when user tries to view dec without transport payment

---

app/uk/gov/hmrc/exports/controllers/SubmissionController.scala
app/uk/gov/hmrc/exports/repositories/DeclarationRepository.scala
app/uk/gov/hmrc/exports/services/SubmissionService.scala
test/it/uk/gov/hmrc/exports/repositories/DeclarationRepositoryTest.scala
test/unit/uk/gov/hmrc/exports/controllers/SubmissionControllerSpec.scala
test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala

After this change, Declaration document in MongoDB has
its status changed to 'complete' at the time of fetching,
instead of updating it later in the process.
This change prevents a situation where calling the
submission process twice in a short period of time
could result in double submission due to race
condition (previously, declaration status was updated
as a separate operation in Mongo, after checking the
status of fetched declaration).

BAU Enhance and simplify declaration submission process

---

app/uk/gov/hmrc/exports/services/notifications/NotificationParser.scala
test/unit/uk/gov/hmrc/exports/services/notifications/NotificationParserSpec.scala
test/util/testdata/notifications/ExampleXmlAndNotificationDetailsPair.scala

If we encounter a WCO Error Pointer that has field '67A' with its own sequence number, ignore the sequence number.

[CEDS-3527] Skip 67A which has no sequence number

---

app/uk/gov/hmrc/exports/models/declaration/Transport.scala
app/uk/gov/hmrc/exports/services/mapping/declaration/BorderTransportMeansBuilder.scala
app/uk/gov/hmrc/exports/util/ExportsDeclarationBuilder.scala
test/unit/uk/gov/hmrc/exports/services/mapping/declaration/BorderTransportMeansBuilderSpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/ConsignmentBuilderSpec.scala

Fix two issues:
1) When empty string values sent builder was producing schema non-compliant XML (e.g. <ns3:ID/> & <ns3:IdentificationTypeCode/>)
2) When BorderTransport does not specify an ID & IdentificationTypeCode so we use the DepartureTransport values instead, we were not
populating the RegistrationNationalityCode element with the value specified in BorderTransport

[BAU] Fix payload building issues

---

app/uk/gov/hmrc/exports/repositories/SubmissionRepository.scala
app/uk/gov/hmrc/exports/services/notifications/receiptactions/ParseAndSaveAction.scala
test/it/uk/gov/hmrc/exports/repositories/SubmissionRepositorySpec.scala
test/unit/uk/gov/hmrc/exports/base/UnitTestMockBuilder.scala
test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala
test/unit/uk/gov/hmrc/exports/services/notifications/NotificationServiceSpec.scala
test/unit/uk/gov/hmrc/exports/services/notifications/receiptactions/ParseAndSaveActionSpec.scala

There was a bug where as the fetching of the submission record happened for each notification before any of the
conditional updates occur, this resulted in the first update being successful but all the subsequent
updates failing (due to its condition no longer being satisfied).
I've removed the condition on the update which will mean unnecessary MRN updates happening for now. Will come bakc to this for
a better solution later.

[CEDS-3784] Optimisation bug fix

---

app/uk/gov/hmrc/exports/services/notifications/receiptactions/ParseAndSaveAction.scala
test/unit/uk/gov/hmrc/exports/services/notifications/receiptactions/ParseAndSaveActionSpec.scala
test/util/testdata/RepositoryTestData.scala

Instead of performing for each notification:
* a find query & optional update query on submission collection
* plus an insert into the notifications collection
We now perform just a single query & optional update query on submission collection
that covers all notifications (as all notifications share the same actionId when
received in a single endpoint call), and a single bulk insert operation that covers
all notifications being processed.

[CEDS-3784] Further optimisations

---

app/uk/gov/hmrc/exports/controllers/testonly/GenerateSubmittedDecController.scala
app/uk/gov/hmrc/exports/models/ead/parsers/DateParser.scala
app/uk/gov/hmrc/exports/services/notifications/NotificationParser.scala
app/uk/gov/hmrc/exports/util/ExportsDeclarationBuilder.scala
test/unit/uk/gov/hmrc/exports/models/declaration/notifications/ParsedNotificationSpec.scala
test/unit/uk/gov/hmrc/exports/models/ead/MrnStatusSpec.scala
test/unit/uk/gov/hmrc/exports/models/ead/parsers/MrnStatusParserSpec.scala
test/unit/uk/gov/hmrc/exports/scheduler/jobs/emails/EmailCancellationValidatorSpec.scala
test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala
test/unit/uk/gov/hmrc/exports/services/notifications/NotificationParserSpec.scala
test/unit/uk/gov/hmrc/exports/services/notifications/NotificationServiceSpec.scala
test/util/testdata/SubmissionTestData.scala
test/util/testdata/notifications/ExampleXmlAndNotificationDetailsPair.scala
test/util/testdata/notifications/NotificationTestData.scala

Fix bug when parsing dateTime values in the notification XML payload.
We were converting offset datTime values such as '20220401102910+01' into
UTC values of '2022-04-01T10:29:10Z[UTC]' (not adjusting for the offset!).
This meant that when we displayed these values to the user and adjusted for
BST we were adding +1 hour to the actual dateTime value.

CEDS-3854 notification date time parsing bug

---

app/uk/gov/hmrc/exports/scheduler/Scheduler.scala
app/uk/gov/hmrc/exports/scheduler/jobs/PurgeAncientSubmissionsJob.scala
app/uk/gov/hmrc/exports/scheduler/jobs/PurgeDraftDeclarationsJob.scala
conf/logback.xml

Ensure jobs log when they start executing aswell as when they finish.
Silence mongodb driver filling logs with junk

BAU Adding Extra logging for scheduler

---

app/uk/gov/hmrc/exports/controllers/testonly/GenerateDraftDecController.scala

Country names used to populate new draft declarations created via the test-only endpoint were using non-standard country names. As a result when the XML was generated for that declaration the country element was missing (as no match could be found).

BAU_Fix test-only Country names not matching

---

project/AppDependencies.scala

The other vulnerability listed for this service addressed here: https://confluence.tools.tax.service.gov.uk/display/CD/Vulnerability+XStream+CVE-2021-21345

CEDS-4218 Upgrade hmrc mongo to remove jsoup vulnerability

---

app/uk/gov/hmrc/exports/controllers/testonly/GenerateSubmittedDecController.scala
app/uk/gov/hmrc/exports/migrations/MigrationRoutine.scala
app/uk/gov/hmrc/exports/migrations/changelogs/notification/AddVersionField.scala
app/uk/gov/hmrc/exports/models/declaration/notifications/NotificationDetails.scala
app/uk/gov/hmrc/exports/repositories/SubmissionRepository.scala
app/uk/gov/hmrc/exports/repositories/UpdateSubmissionsTransactionalOps.scala
app/uk/gov/hmrc/exports/services/notifications/NotificationParser.scala
test/it/uk/gov/hmrc/exports/migrations/changelogs/notification/AddVersionFieldISpec.scala
test/it/uk/gov/hmrc/exports/migrations/changelogs/submission/AddNotificationSummariesToSubmissionsISpec.scala
test/it/uk/gov/hmrc/exports/repositories/UpdateSubmissionsTransactionalOpsISpec.scala
test/it/uk/gov/hmrc/exports/scheduler/jobs/PurgeAncientSubmissionsJobISpec.scala
test/it/uk/gov/hmrc/exports/services/notifications/receiptactions/ParseAndSaveActionISpec.scala
test/unit/uk/gov/hmrc/exports/models/declaration/notifications/ParsedNotificationSpec.scala
test/unit/uk/gov/hmrc/exports/scheduler/jobs/emails/EmailCancellationValidatorSpec.scala
test/unit/uk/gov/hmrc/exports/services/notifications/NotificationServiceSpec.scala
test/util/testdata/notifications/ExampleXmlAndNotificationDetailsPair.scala
test/util/testdata/notifications/NotificationTestData.scala

When receiving amendment notifications, ensure that only notifications with a declaration VersionID value greater than the corresponding declaration's cached latestVersionNo are processed. Those with VersionID less than or equal to the corresponding declaration's cached latestVersionNo are ignored.

CEDS-4736_Amendment_Notifications_are_treated_like_external_amendments

---

app/uk/gov/hmrc/exports/models/declaration/notifications/NotificationError.scala
app/uk/gov/hmrc/exports/services/notifications/NotificationParser.scala
project/plugins.sbt
test/unit/uk/gov/hmrc/exports/services/notifications/NotificationParserSpec.scala
test/util/testdata/notifications/ExampleXmlAndNotificationDetailsPair.scala

The <error> elements sometimes contain child <description> elements. This change will mean that we capture this info in our mongo store

CEDS-5025 Parse and store Description element from error notifications

---

app/uk/gov/hmrc/exports/config/AppConfig.scala
app/uk/gov/hmrc/exports/models/declaration/submissions/SubmissionStatus.scala
app/uk/gov/hmrc/exports/services/audit/AuditNotifications.scala
app/uk/gov/hmrc/exports/services/audit/AuditService.scala
app/uk/gov/hmrc/exports/services/notifications/receiptactions/ParseAndSaveAction.scala
test/it/uk/gov/hmrc/exports/repositories/UpdateSubmissionsTransactionalOpsISpec.scala
test/it/uk/gov/hmrc/exports/services/notifications/receiptactions/ParseAndSaveActionISpec.scala
test/unit/uk/gov/hmrc/exports/services/notifications/receiptactions/ParseAndSaveActionSpec.scala
test/util/testdata/notifications/NotificationTestData.scala

Creates audit events that reports the returned function codes of the processed notifications and the distinct list of any error codes they contain.

CEDS-5206 Add new event on Notification Processing

---

app/uk/gov/hmrc/exports/migrations/changelogs/cache/AddAssociatedSubmissionIdToDeclarations.scala
app/uk/gov/hmrc/exports/models/declaration/ExportsDeclaration.scala
test/it/uk/gov/hmrc/exports/migrations/changelogs/submission/AddAssociatedSubmissionToDeclarationsISpec.scala

The ExportsDeclarationRequest was making a field by field copy of the DeclarationMetaData object rather than just copying the entire thing. This resulted in the new `associatedSubmissionId` field being stripped out of any updates to a draft declaration.
I've also renamed the migration job that populates the new `associatedSubmissionId` field so that it runs again in production to re-populate those declarations that will now be missing the new fields.

CEDS-5592 Fix transformation from ExportsDeclarationRequest

---

app/uk/gov/hmrc/exports/connectors/CustomsDeclarationsConnector.scala
app/uk/gov/hmrc/exports/repositories/UpdateSubmissionsTransactionalOps.scala
app/uk/gov/hmrc/exports/services/mapping/declaration/AdditionalInformationBuilder.scala
app/uk/gov/hmrc/exports/services/notifications/receiptactions/NotificationReceiptActionsRunner.scala
test/it/uk/gov/hmrc/exports/connector/CustomsDeclarationsConnectorISpec.scala
test/unit/uk/gov/hmrc/exports/services/mapping/declaration/AdditionalInformationBuilderSpec.scala

Replacing line feed and carriage return chars in the amendment `statementDescription` field with space characters to ensure generated XML is schema compliant.
Also fixing error reporting on downstream connector to stop reporting 400s errors as 500s in the logs.
Finally, some logging tweaks:
* stop logging at error level when submission is not updated that we can't delete any associated draft amendments
* add comment that when we fail to process a notification that we will reattempt it.

CEDS-5759 Fix Sending invalid XML payload to DEC API for amendments
