app/uk/gov/hmrc/exports/controllers/ResponseHandlerController.scala, app/uk/gov/hmrc/exports/controllers/actions/ExportController.scala, app/uk/gov/hmrc/exports/models/Submission.scala, app/uk/gov/hmrc/exports/repositories/SubmissionRepository.scala, test/uk/gov/hmrc/exports/base/AuthTestSupport.scala, test/uk/gov/hmrc/exports/base/CustomsExportsBaseSpec.scala, test/uk/gov/hmrc/exports/base/SubmissionData.scala, test/uk/gov/hmrc/exports/controllers/ResponseHandlerControllerSpec.scala, test/uk/gov/hmrc/exports/controllers/actions/ExportControllerSpec.scala, test/uk/gov/hmrc/exports/repositories/SubmissionRepositorySpec.scala
Fixed import relates with `Inject`.
Small style changes.
Divided tests to two cases
=> Cleaning and fixing code

app/uk/gov/hmrc/exports/controllers/SubmissionController.scala, app/uk/gov/hmrc/exports/models/Submission.scala, test/uk/gov/hmrc/exports/base/ExportsTestData.scala
Related with frontend PR: https://github.com/hmrc/customs-declare-exports-frontend/pull/60
=> CEDS-831 Added handling for lrn and mrn

test/uk/gov/hmrc/exports/base/AuthTestSupport.scala, test/uk/gov/hmrc/exports/base/CustomsExportsBaseSpec.scala, test/uk/gov/hmrc/exports/base/ExportsTestData.scala, test/uk/gov/hmrc/exports/config/AppConfigSpec.scala, test/uk/gov/hmrc/exports/controllers/NotificationsControllerSpec.scala, test/uk/gov/hmrc/exports/controllers/SubmissionControllerSpec.scala, test/uk/gov/hmrc/exports/controllers/actions/ExportControllerSpec.scala, test/uk/gov/hmrc/exports/repositories/MovementNotificationsRepositorySpec.scala, test/uk/gov/hmrc/exports/repositories/MovementRepositorySpec.scala, test/uk/gov/hmrc/exports/repositories/NotificationsRepositorySpec.scala, test/uk/gov/hmrc/exports/repositories/SubmissionRepositorySpec.scala
Some code refactoring:
- put empty eori to userWithoutEori method (was a bit confusing)
- fixed SubmissionRepositorySpec race conditions (beforeAll/afterAll seems to not work properly in our cases, changed to beforeEach/afterEach)
- changed test descriptions (to be more readable)
- added few TODOs (after consultations with Patryk)
=> CDS-999 Backend tests review

app/uk/gov/hmrc/exports/controllers/HeaderValidator.scala, app/uk/gov/hmrc/exports/controllers/NotificationsController.scala, app/uk/gov/hmrc/exports/models/AuthorisedRequest.scala, test/uk/gov/hmrc/exports/controllers/HeaderValidatorSpec.scala, test/uk/gov/hmrc/exports/controllers/NotificationsControllerSpec.scala
This was missed on the previous PR so removing this validation for submission notifications
=> CEDS-1074: eori header not validated on submission notifications

test/integration/uk/gov/hmrc/exports/repositories/NotificationsRepositorySpec.scala, test/integration/uk/gov/hmrc/exports/repositories/SubmissionRepositorySpec.scala, test/integration/uk/gov/hmrc/exports/services/ExportsServiceSpec.scala, test/util/CustomsDeclarationsAPIConfig.scala, test/util/ExportsTestData.scala, test/util/stubs/CustomsDeclarationsAPIService.scala
- split test for notification, submission
- added tests for cancellation
=> * CEDS-1193 Move test around in customs-declare-exports *

app/uk/gov/hmrc/exports/controllers/ExportController.scala, app/uk/gov/hmrc/exports/controllers/NotificationsController.scala, app/uk/gov/hmrc/exports/controllers/SubmissionController.scala, app/uk/gov/hmrc/exports/models/DeclarationNotification.scala, app/uk/gov/hmrc/exports/repositories/SubmissionRepository.scala, app/uk/gov/hmrc/exports/services/NotificationService.scala, build.sbt, test/unit/uk/gov/hmrc/exports/base/AuthTestSupport.scala, test/unit/uk/gov/hmrc/exports/base/CustomsExportsBaseSpec.scala, test/unit/uk/gov/hmrc/exports/controllers/NotificationsControllerSpec.scala, test/unit/uk/gov/hmrc/exports/controllers/SubmissionControllerSpec.scala, test/unit/uk/gov/hmrc/exports/models/CancellationStatusSpec.scala, test/unit/uk/gov/hmrc/exports/models/DeclarationNotificationSpec.scala, test/unit/uk/gov/hmrc/exports/services/NotificationsServiceSpec.scala
Additionally changed Retrievals to use not deprecated and the same with body parsers.
=> CEDS-1215: created notification service and added tests

test/unit/uk/gov/hmrc/exports/controllers/SubmissionControllerSpec.scala
- added test for cancellation without EORI
=> * CEDS-1210 Non authorised tests for Submission Controller *

app/uk/gov/hmrc/exports/controllers/request/ExportsDeclarationRequest.scala, app/uk/gov/hmrc/exports/models/declaration/ExportsDeclaration.scala, app/uk/gov/hmrc/exports/models/declaration/TransportInformationContainers.scala, app/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/ConsignmentBuilder.scala, app/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/TransportEquipmentBuilder.scala, test/component/uk/gov/hmrc/exports/ExportsSubmissionReceivedSpec.scala, test/uk/gov/hmrc/exports/controllers/request/ExportsDeclarationRequestSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/ConsignmentBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/TransportEquipmentBuilderSpec.scala, test/util/testdata/ExportsDeclarationBuilder.scala, test/util/testdata/ExportsTestData.scala
This is the back-end model change for containers and seals.   It will probably break existing acceptance tests (although, declarations with containers/seals are already broken to some extent) so I'd advise not merging until the frontend changes are ready.
=> CEDS-1405 - model change for containers and seals

app/uk/gov/hmrc/exports/services/mapping/goodsshipment/PreviousDocumentsBuilder.scala, app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilder.scala
No Jira ticket for this.   Following the recent bug with BigDecimal creation from double values, I found these couple of proposed changes which might be worth merging.
=> BAU - proposed minor changes to the way we create java.math.BigDecimal

app/uk/gov/hmrc/exports/services/mapping/goodsshipment/GoodsShipmentBuilder.scala, app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilder.scala, test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/GoodsShipmentBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilderSpec.scala
As part of this change we should not map Commodity Measurements and
Nature of Transaction, as they are not needed for the Simplified journey
=> CEDS-1851 Adjust DMS mapping for implified Journey

app/uk/gov/hmrc/exports/models/declaration/ExportItem.scala, app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/StatisticalValueAmountBuilder.scala, conf/code-lists/pointer-mapping.csv, test/unit/uk/gov/hmrc/exports/services/mapping/CachingMappingHelperSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/ExportsItemBuilder.scala, test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemData.scala, test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/StatisticalValueAmountBuilderSpec.scala, test/util/SeedMongo.scala
This also includes updates to the pointer mapping file which I presume are needed for the recent changes
=> CEDS-1968 - rename ItemType to StatisticalValue

app/uk/gov/hmrc/exports/config/AppConfig.scala, app/uk/gov/hmrc/exports/connectors/ead/CustomsDeclarationsInformationConnector.scala, app/uk/gov/hmrc/exports/controllers/ead/EADController.scala, app/uk/gov/hmrc/exports/models/ead/MrnStatus.scala, app/uk/gov/hmrc/exports/models/ead/PreviousDocument.scala, app/uk/gov/hmrc/exports/models/ead/XmlTags.scala, app/uk/gov/hmrc/exports/models/ead/parsers/MrnStatusParser.scala, app/uk/gov/hmrc/exports/models/ead/parsers/StringOption.scala, conf/app.routes, conf/application.conf, test/it/uk/gov/hmrc/exports/connector/ead/CustomsDeclarationsInformationConnectorSpec.scala, test/unit/uk/gov/hmrc/exports/config/AppConfigSpec.scala, test/unit/uk/gov/hmrc/exports/controllers/ead/EADControllerSpec.scala, test/unit/uk/gov/hmrc/exports/models/ead/MrnStatusSpec.scala, test/unit/uk/gov/hmrc/exports/models/ead/parsers/MrnStatusParserSpec.scala, test/unit/uk/gov/hmrc/exports/models/ead/parsers/MrnStatusParserTestData.scala, test/util/stubs/CustomsDeclarationsInformationAPIConfig.scala, test/util/stubs/CustomsDeclarationsInformationAPIService.scala
This will be the config needed to connect with the Declaration
Information Service (DIS).
=> CEDS-2171 CEDS-2171 - Add customs-declarations-informations config

app/uk/gov/hmrc/exports/models/ead/parsers/MrnStatusParser.scala, test/unit/uk/gov/hmrc/exports/models/ead/parsers/MrnStatusParserSpec.scala
DUCR should be the first item from the PreviousDocuments of type `DCR`
=> CEDS-2171 Fix DUCR mapping from DIS

app/uk/gov/hmrc/exports/models/declaration/Locations.scala, app/uk/gov/hmrc/exports/models/declaration/ModeOfTransportCode.scala, app/uk/gov/hmrc/exports/models/declaration/Transport.scala, app/uk/gov/hmrc/exports/services/mapping/declaration/BorderTransportMeansBuilder.scala, app/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/DepartureTransportMeansBuilder.scala, test/unit/uk/gov/hmrc/exports/services/mapping/declaration/BorderTransportMeansBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/GoodsShipmentBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/ConsignmentBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/consignment/DepartureTransportMeansBuilderSpec.scala, test/util/stubs/SeedMongo.scala, test/util/testdata/ExportsDeclarationBuilder.scala
This is used for Transport.borderModeOfTransportCode and
InlandModeOfTransportCode.
=> CEDS-2250 Introduce ModeOfTransportCodes type

app/uk/gov/hmrc/exports/mongock/changesets/CacheChangeLog.scala
We are going to try and understand what is happening with the executions
of DB migrations on the remote environments by debugging entry points
and each document being updated.
=> BAU - Understand DB migrations on remove environments

app/uk/gov/hmrc/exports/models/declaration/Locations.scala, test/unit/uk/gov/hmrc/exports/models/declaration/ExportsDeclarationSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/declaration/ExitOfficeBuilderSpec.scala, test/util/testdata/ExportsDeclarationBuilder.scala
**Depends on:**
* https://github.com/hmrc/cds-exports-acceptance/pull/428
=> CEDS-2366 Add Office of Exit Outside UK

app/uk/gov/hmrc/exports/models/declaration/Parties.scala, app/uk/gov/hmrc/exports/services/mapping/declaration/DeclarantBuilder.scala, test/unit/uk/gov/hmrc/exports/services/mapping/declaration/DeclarantBuilderSpec.scala, test/util/testdata/ExportsDeclarationBuilder.scala
If PersonPresentingGoodsDetails is present in the model and it is
Entry Into Declarant's Records, then there should be Person Presenting
Goods EORI put in place of Declarant's ID.
=> CEDS-2450 Add PersonPresentingGoodsDetails to payload as Declarant

project/AppDependencies.scala
* Added Communication to Carrier
* Removed Manufacturer and RefundRecipientParty
* Sequence Numeric is now mandatory on WriteOffQuantityQuantityType
=> CEDS-2499 Schema update

app/uk/gov/hmrc/exports/controllers/request/ExportsDeclarationRequest.scala, app/uk/gov/hmrc/exports/models/declaration/DeclarationStatus.scala, test/unit/uk/gov/hmrc/exports/controllers/request/ExportsDeclarationRequestSpec.scala
Introduced new declaration status, pre-DRAFT
=> CEDS-2469 - Change the Save and Continue button to Continue

app/uk/gov/hmrc/exports/models/ead/MrnStatus.scala, app/uk/gov/hmrc/exports/models/ead/parsers/DateParser.scala, app/uk/gov/hmrc/exports/models/ead/parsers/MrnStatusParser.scala, test/unit/uk/gov/hmrc/exports/models/ead/MrnStatusSpec.scala, test/unit/uk/gov/hmrc/exports/models/ead/parsers/MrnStatusParserSpec.scala, test/unit/uk/gov/hmrc/exports/models/ead/parsers/MrnStatusParserTestData.scala
=> CEDS-2628 - change to single-digit hour format for MrnStaus

build.sbt, project/TestPhases.scala, project/build.properties, project/plugins.sbt, test/it/uk/gov/hmrc/exports/mongock/changesets/SubmissionsChangeLogSpec.scala, test/it/uk/gov/hmrc/exports/repositories/DeclarationRepositoryTest.scala
This version seems to be the last reliable version.
Higher versions contain some issues with importing a project. That would
need additional steps and workarounds to make it work.
=> CEDS-2659 Upgrade SBT to 1.3.6

app/uk/gov/hmrc/exports/repositories/DeclarationRepository.scala, app/uk/gov/hmrc/exports/repositories/NotificationRepository.scala, app/uk/gov/hmrc/exports/repositories/RepositorySettings.scala, app/uk/gov/hmrc/exports/repositories/SubmissionRepository.scala
In order to increase resilience of the service, this PR
implements a FailoverStrategy for ReactiveMongo.
=> CEDS-2776 Implement FailoverStrategy for all repository classes

app/uk/gov/hmrc/exports/migrations/ExportsMigrationTool.scala
Previously it only seemed to log on specific exception
classes. Now will log with any throwable.
=> [CEDS-2800] Add exception logging to DB migration tool

project/AppDependencies.scala, project/plugins.sbt, test/it/uk/gov/hmrc/exports/base/IntegrationTestSpec.scala, test/it/uk/gov/hmrc/exports/util/TestModule.scala
Upgrade service to Play 2.7.9 and update dependencies
=> CEDS-2940 Upgrade to Play 2.7

app/uk/gov/hmrc/exports/controllers/NotificationController.scala, app/uk/gov/hmrc/exports/repositories/NotificationRepository.scala, app/uk/gov/hmrc/exports/services/notifications/NotificationFactory.scala, app/uk/gov/hmrc/exports/services/notifications/NotificationService.scala, test/it/uk/gov/hmrc/exports/repositories/NotificationRepositorySpec.scala, test/unit/uk/gov/hmrc/exports/base/UnitTestMockBuilder.scala, test/unit/uk/gov/hmrc/exports/controllers/NotificationControllerSpec.scala, test/unit/uk/gov/hmrc/exports/services/notifications/NotificationFactorySpec.scala, test/unit/uk/gov/hmrc/exports/services/notifications/NotificationServiceSpec.scala, test/util/testdata/RepositoryTestData.scala
This PR contains some refactoring required
for the asynchronous notifications processing
feature.
The main reason for this refactor is to simplify
a few methods and therefore the whole process.
=> CEDS-3036 asynchronous notification processing

app/uk/gov/hmrc/exports/services/SubmissionService.scala, app/uk/gov/hmrc/exports/services/notifications/receiptactions/SendEmailForDmsDocAction.scala, test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala
This PR covers email triggering in a scenario when
Notifications come before saving Submission 
document.
=> CEDS-2975 Add email triggering in a corner-case scenario

app/uk/gov/hmrc/exports/controllers/EmailByEoriController.scala, app/uk/gov/hmrc/exports/controllers/NotificationController.scala, app/uk/gov/hmrc/exports/models/declaration/notifications/Notification.scala, app/uk/gov/hmrc/exports/models/declaration/notifications/ParsedNotification.scala, app/uk/gov/hmrc/exports/models/declaration/notifications/UnparsedNotification.scala, app/uk/gov/hmrc/exports/repositories/NotificationRepository.scala, app/uk/gov/hmrc/exports/scheduler/jobs/emails/EmailCancellationValidator.scala, app/uk/gov/hmrc/exports/scheduler/jobs/emails/SendEmailsJob.scala, app/uk/gov/hmrc/exports/services/SubmissionService.scala, app/uk/gov/hmrc/exports/services/notifications/NotificationFactory.scala, app/uk/gov/hmrc/exports/services/notifications/NotificationService.scala, app/uk/gov/hmrc/exports/services/notifications/receiptactions/NotificationReceiptActionsExecutor.scala, app/uk/gov/hmrc/exports/services/notifications/receiptactions/ParseAndSaveAction.scala, app/uk/gov/hmrc/exports/services/notifications/receiptactions/SendEmailForDmsDocAction.scala, test/component/uk/gov/hmrc/exports/steps/SubmissionSteps.scala, test/it/uk/gov/hmrc/exports/repositories/NotificationRepositorySpec.scala, test/unit/uk/gov/hmrc/exports/controllers/NotificationControllerSpec.scala, test/unit/uk/gov/hmrc/exports/models/declaration/notifications/NotificationSpec.scala, test/unit/uk/gov/hmrc/exports/models/declaration/notifications/ParsedNotificationSpec.scala, test/unit/uk/gov/hmrc/exports/scheduler/jobs/emails/EmailCancellationValidatorSpec.scala, test/unit/uk/gov/hmrc/exports/scheduler/jobs/emails/SendEmailsJobSpec.scala, test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala, test/unit/uk/gov/hmrc/exports/services/email/EmailSenderSpec.scala, test/unit/uk/gov/hmrc/exports/services/notifications/NotificationFactorySpec.scala, test/unit/uk/gov/hmrc/exports/services/notifications/NotificationServiceSpec.scala, test/unit/uk/gov/hmrc/exports/services/notifications/receiptactions/NotificationReceiptActionsExecutorSpec.scala, test/unit/uk/gov/hmrc/exports/services/notifications/receiptactions/ParseAndSaveActionSpec.scala, test/unit/uk/gov/hmrc/exports/services/notifications/receiptactions/SendEmailForDmsDocActionSpec.scala, test/util/matchers/NotificationMatchers.scala, test/util/testdata/notifications/NotificationTestData.scala
Email Notification for DMSDOC status is now
cancelled if there is a Notification received after
DMSDOC that contains one of the statuses:
- DMSCLE
- DMSINV
- DMSREJ
In case there is another DMSDOC received after one
of the 3 statuses above, email notification will be sent.
The 3 statuses above cancels any number of email 
notifications that were before.
=> CEDS-3081 Stop email sending

app/uk/gov/hmrc/exports/models/declaration/TransportPayment.scala, app/uk/gov/hmrc/exports/services/mapping/declaration/consignment/FreightBuilder.scala, test/unit/uk/gov/hmrc/exports/models/declaration/TransportSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/declaration/consignment/FreightBuilderSpec.scala, test/util/testdata/ExportsDeclarationBuilder.scala
Adding in new payment option value that when
present should not be sent to DMS as part of
the XML payload.
=> [CEDS-3182] New transport payment option

app/uk/gov/hmrc/exports/connectors/ead/CustomsDeclarationsInformationConnector.scala
Explicitly adding the Authorization header to the headers sent
by the connector. This must of been automaically done pre 2.8
=> [CEDS-3267] Fix EAD connector

app/uk/gov/hmrc/exports/models/declaration/ConsignmentReferences.scala, app/uk/gov/hmrc/exports/services/mapping/goodsshipment/GoodsShipmentBuilder.scala, app/uk/gov/hmrc/exports/services/mapping/goodsshipment/PreviousDocumentsBuilder.scala, test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/GoodsShipmentBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/PreviousDocumentsBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/UCRBuilderSpec.scala, test/util/testdata/ExportsDeclarationBuilder.scala, test/util/testdata/ExportsTestData.scala
Add new mrn and eidrDateStamp fields to the
consignment references model entity.
=> [CEDS-3296] Supplementary Backend data model update

app/uk/gov/hmrc/exports/services/reversemapping/declaration/ExportsDeclarationXmlParser.scala, app/uk/gov/hmrc/exports/services/reversemapping/declaration/XmlTags.scala, app/uk/gov/hmrc/exports/services/reversemapping/declaration/transport/ContainersParser.scala, app/uk/gov/hmrc/exports/services/reversemapping/declaration/transport/TransportParser.scala, test/unit/uk/gov/hmrc/exports/services/reversemapping/declaration/ExportsDeclarationXmlParserSpec.scala, test/unit/uk/gov/hmrc/exports/services/reversemapping/declaration/transport/ContainersParserSpec.scala, test/unit/uk/gov/hmrc/exports/services/reversemapping/declaration/transport/TransportParserSpec.scala
Adding in Transport -> Containers parsing
=> [CEDS-3349] XML to ExportsDeclaration mapping Group 2

app/uk/gov/hmrc/exports/controllers/NotificationController.scala, app/uk/gov/hmrc/exports/controllers/SubmissionController.scala, app/uk/gov/hmrc/exports/models/declaration/submissions/SubmissionQueryParameters.scala, app/uk/gov/hmrc/exports/repositories/SubmissionRepository.scala, app/uk/gov/hmrc/exports/services/SubmissionService.scala, app/uk/gov/hmrc/exports/services/notifications/NotificationService.scala, conf/app.routes, test/it/uk/gov/hmrc/exports/repositories/SubmissionRepositorySpec.scala, test/unit/uk/gov/hmrc/exports/base/UnitTestMockBuilder.scala, test/unit/uk/gov/hmrc/exports/controllers/NotificationControllerSpec.scala, test/unit/uk/gov/hmrc/exports/controllers/SubmissionControllerSpec.scala, test/unit/uk/gov/hmrc/exports/models/declaration/submissions/SubmissionQueryParametersSpec.scala, test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala, test/unit/uk/gov/hmrc/exports/services/notifications/NotificationServiceSpec.scala
This PR presents a WIP for unifying the API and implementation
for fetching Submissions using different parameters.
=> CEDS-3410 Implement single route for fetching Submission

conf/app.routes
These two endpoints are going to replace the existing
ones. However, the old endpoints will be removed later,
once services using them are updated.
=> CEDS-3410 Create new endpoints for Notifications and Submissions

app/uk/gov/hmrc/exports/controllers/SubmissionController.scala, conf/app.routes, test/unit/uk/gov/hmrc/exports/controllers/NotificationControllerSpec.scala, test/unit/uk/gov/hmrc/exports/controllers/SubmissionControllerSpec.scala
There are new endpoints with the exact same
functionality.
=> CEDS-3410 Remove redundant endpoints

app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/AdditionalDocumentsBuilder.scala, test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/AdditionalDocumentsBuilderSpec.scala
Set AdditionalDocument fields to some default values if
other fields match certain conditions.
=> [CEDS-3404] CDS bug work around for Doc identifier

app/uk/gov/hmrc/exports/services/mapping/declaration/CurrencyExchangeBuilder.scala, app/uk/gov/hmrc/exports/services/mapping/declaration/InvoiceAmountBuilder.scala, test/unit/uk/gov/hmrc/exports/services/mapping/declaration/CurrencyExchangeBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/declaration/InvoiceAmountBuilderSpec.scala
Strip commas from values if present and ensure values that start
or end with a period are properly handled (normalised).
=> [CEDS-3478] Normalise invoice amount and exchange rate values

app/uk/gov/hmrc/exports/models/declaration/PreviousDocuments.scala, app/uk/gov/hmrc/exports/models/declaration/submissions/SubmissionQueryParameters.scala, app/uk/gov/hmrc/exports/services/mapping/goodsshipment/PreviousDocumentsBuilder.scala, test/unit/uk/gov/hmrc/exports/models/declaration/ExportsDeclarationSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/goodsshipment/PreviousDocumentsBuilderSpec.scala, test/util/stubs/SeedMongo.scala
Remove documentCategory from model and hardcode `Previous_Document.CategoryCode` to `Z`
=> CEDS-3103 Amend 'Previous_Document' model

app/uk/gov/hmrc/exports/controllers/CancellationController.scala, app/uk/gov/hmrc/exports/models/declaration/submissions/CancellationStatus.scala, app/uk/gov/hmrc/exports/repositories/SubmissionRepository.scala, app/uk/gov/hmrc/exports/services/SubmissionService.scala, test/it/uk/gov/hmrc/exports/repositories/SubmissionRepositorySpec.scala, test/unit/uk/gov/hmrc/exports/controllers/CancellationControllerSpec.scala, test/unit/uk/gov/hmrc/exports/models/declaration/submissions/CancellationStatusSpec.scala, test/unit/uk/gov/hmrc/exports/services/SubmissionServiceSpec.scala
Check that the user has permissions to the MRN provided before
making the request to DMS. If the user does not have permission
then display form field errors (rather than just 500 Internal
Server error page).
=> CEDS-1965] Handling cancellation of non-existing declaration

app/uk/gov/hmrc/exports/services/mapping/declaration/AdditionalInformationBuilder.scala, app/uk/gov/hmrc/exports/services/mapping/declaration/DeclarationBuilder.scala, app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/AdditionalInformationBuilder.scala, test/unit/uk/gov/hmrc/exports/services/mapping/declaration/AdditionalInformationBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/AdditionalInformationBuilderSpec.scala
Add new AdditionalInformation element at header level with StatementCode value of 'RRS01'
and StatementDescription value of carrier's EORI or address full name.
=> [CEDS-3681] Auto-populate RRS01 for GVMS declarations

README.md, app/uk/gov/hmrc/exports/controllers/testonly/GenerateDraftDecController.scala, app/uk/gov/hmrc/exports/util/ExportsDeclarationBuilder.scala, app/uk/gov/hmrc/exports/util/ExportsItemBuilder.scala, conf/testOnlyDoNotUseInAppConf.routes, test/unit/uk/gov/hmrc/exports/controllers/testonly/GenerateDraftDecControllerSpec.scala, test/unit/uk/gov/hmrc/exports/controllers/testonly/GenerateSubmittedDecControllerSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/declaration/AdditionalInformationBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/AdditionalInformationBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/GovernmentProcedureBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/PackagingBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/StatisticalValueAmountBuilderSpec.scala, test/unit/uk/gov/hmrc/exports/services/reversemapping/declaration/parties/PartiesParserSpec.scala, test/util/stubs/SeedMongo.scala
Creation of new test-only endpoint to create a draft
declaration with the specified number of items.
=> [CEDS-3808] Create draft dec with X line items

app/uk/gov/hmrc/exports/repositories/DeclarationRepository.scala
Swapping search keys to match order defined in mongo index
=> BAU Performance tweak

app/uk/gov/hmrc/exports/repositories/TransactionalOps.scala
=> BAU Fix the search filter used on updating a Submission with new Notifications

app/uk/gov/hmrc/exports/migrations/changelogs/cache/AddSequencingOfMultipleItems.scala
This generally happens with broken documents (they don't have the expected format)
=> CEDS-4370 Fix for when, while applying a migration, parsing documents triggers an exception

app/uk/gov/hmrc/exports/services/mapping/ExportsPointerToWCOPointer.scala, test/it/uk/gov/hmrc/exports/services/mapping/ExportsPointerToWCOPointerISpec.scala, test/unit/uk/gov/hmrc/exports/services/mapping/ExportsPointerToWCOPointerSpec.scala
ExportsPointerToWCOPointerLoader has a val that was requesting access to a resource file "conf/exports-wco-mapping.csv" before the classloader was ready.
=> BAU Fix_class_loader_resource_issue

app/uk/gov/hmrc/exports/migrations/changelogs/notification/AddVersionField.scala
Enable the new db migration job for CEDS-4736
=> CEDS-4736 Enable migration job

app/uk/gov/hmrc/exports/controllers/DeclarationController.scala, app/uk/gov/hmrc/exports/services/DeclarationService.scala, app/uk/gov/hmrc/exports/util/ExportsDeclarationBuilder.scala, conf/app.routes, test/it/uk/gov/hmrc/exports/services/DeclarationServiceISpec.scala, test/unit/uk/gov/hmrc/exports/controllers/DeclarationControllerSpec.scala
=> CEDS-5159 Add new BE endpoint to return draft declaration

app/uk/gov/hmrc/exports/models/JobRun.scala, app/uk/gov/hmrc/exports/repositories/DeclarationRepository.scala, app/uk/gov/hmrc/exports/repositories/JobRunRepository.scala, app/uk/gov/hmrc/exports/repositories/ParsedNotificationRepository.scala, app/uk/gov/hmrc/exports/repositories/RepositoryOps.scala, app/uk/gov/hmrc/exports/repositories/SendEmailWorkItemRepository.scala, app/uk/gov/hmrc/exports/repositories/SubmissionRepository.scala, app/uk/gov/hmrc/exports/repositories/UnparsedNotificationWorkItemRepository.scala, app/uk/gov/hmrc/exports/scheduler/Scheduler.scala, app/uk/gov/hmrc/exports/scheduler/SchedulerDateUtil.scala, app/uk/gov/hmrc/exports/scheduler/jobs/PurgeAncientSubmissionsJob.scala, app/uk/gov/hmrc/exports/scheduler/jobs/PurgeDraftDeclarationsJob.scala, app/uk/gov/hmrc/exports/services/DeclarationService.scala, project/plugins.sbt, test/it/uk/gov/hmrc/exports/base/IntegrationTestPurgeSubmissionsToolSpec.scala, test/it/uk/gov/hmrc/exports/repositories/DeclarationRepositoryISpec.scala, test/it/uk/gov/hmrc/exports/repositories/JobRunRepositoryISpec.scala, test/it/uk/gov/hmrc/exports/repositories/SubmissionRepositoryISpec.scala, test/unit/uk/gov/hmrc/exports/scheduler/SchedulerSpec.scala, test/unit/uk/gov/hmrc/exports/scheduler/jobs/PurgeAncientSubmissionsJobSpec.scala, test/unit/uk/gov/hmrc/exports/scheduler/jobs/emails/SendEmailsJobSpec.scala, test/unit/uk/gov/hmrc/exports/services/DeclarationServiceSpec.scala
regardless how many instances of the service are spawned
=> CEDS-5355 Ensure any scheduled job runs only once per day

app/uk/gov/hmrc/exports/migrations/changelogs/submission/AddAssociatedSubmissionIdToDeclarations.scala, test/it/uk/gov/hmrc/exports/migrations/changelogs/submission/AddAssociatedSubmissionToDeclarationsISpec.scala
Adding in exclusion for INITIAL status declarations
=> CEDS-5583_Exclude_INITIAL_status_decs

app/uk/gov/hmrc/exports/controllers/DeclarationController.scala, app/uk/gov/hmrc/exports/controllers/NotificationController.scala, app/uk/gov/hmrc/exports/controllers/actions/Authenticator.scala, app/uk/gov/hmrc/exports/features/Feature.scala, app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/AdditionalDocumentsBuilder.scala, app/uk/gov/hmrc/exports/services/mapping/governmentagencygoodsitem/PackagingBuilder.scala, conf/app.routes, precheck.sh
Deleted some redundant endpoints, re-ordered controller methods so that search methods are at the bottom, plus other minor stuff
=> CEDS-6064 Code clean up of Exports BE
